spring.application.name=Session01_IT211_Bai1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456@

spring.datasource.url=jdbc:mysql://localhost:3306/ss02_bai1?createDatabaseIfNotExist=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
